"""Helpers for stable report timestamps and saved report content."""

from __future__ import annotations

import re
from datetime import datetime

# Match any "Date" / "Date of Analysis" / "Date:" line the model may write,
# whether the colon is inside or outside the bold markers.
# Examples this catches:
#   **Date**: 2026-05-08 10:58:10+08:00
#   **Date:** 2026-05-08 10:58:10+08:00
#   **Date of Analysis:** 2026-05-08 10:54:27+08:00
#   **Date of Analysis**: 2026-05-08 ...
DATE_LINE_PATTERN = re.compile(
    r"^\*\*\s*Date(?:\s+of\s+Analysis)?\s*[:*]+\*?\*?\s*[^\n]*$",
    re.MULTILINE | re.IGNORECASE,
)


def current_local_time() -> datetime:
    """Return the current local datetime with timezone information."""
    return datetime.now().astimezone()


def format_local_timestamp(now: datetime | None = None) -> str:
    """Format a local timestamp for saved reports."""
    if now is None:
        now = current_local_time()
    return now.isoformat(sep=" ", timespec="seconds")


def build_report_header_comment(now: datetime | None = None) -> str:
    """Build the HTML comment header stored above saved Markdown reports."""
    return (
        f"<!-- Generated by Memory Forensics Agent at "
        f"{format_local_timestamp(now)} -->\n\n"
    )


def ensure_report_date(content: str, now: datetime | None = None) -> str:
    """Replace every Date/"Date of Analysis" line with one canonical date.

    The model frequently writes its own ``**Date of Analysis:**`` line in
    addition to the ``**Date**:`` line we insert. To avoid duplicate or
    conflicting dates in saved reports, strip all such lines first and then
    insert exactly one canonical ``**Date**:`` line.
    """
    text = (content or "").strip()
    if not text:
        return text

    canonical_date = f"**Date**: {format_local_timestamp(now)}"

    # Strip ALL existing date-style lines the model may have written.
    stripped = DATE_LINE_PATTERN.sub("", text)
    # Collapse runs of blank lines created by the substitution.
    stripped = re.sub(r"\n{3,}", "\n\n", stripped).strip()

    lines = stripped.splitlines()
    if lines and lines[0].startswith("# "):
        lines.insert(1, "")
        lines.insert(2, canonical_date)
        return "\n".join(lines)

    return f"{canonical_date}\n\n{stripped}"
