"""Helpers for stable report timestamps and saved report content."""

from __future__ import annotations

import re
from datetime import datetime

DATE_LINE_PATTERN = re.compile(r"^\*\*Date\*\*:\s*.+$", re.MULTILINE)


def current_local_time() -> datetime:
    """Return the current local datetime with timezone information."""
    return datetime.now().astimezone()


def format_local_timestamp(now: datetime | None = None) -> str:
    """Format a local timestamp for saved reports."""
    if now is None:
        now = current_local_time()
    return now.isoformat(sep=" ", timespec="seconds")


def build_report_header_comment(now: datetime | None = None) -> str:
    """Build the HTML comment header stored above saved Markdown reports."""
    return (
        f"<!-- Generated by Memory Forensics Agent at "
        f"{format_local_timestamp(now)} -->\n\n"
    )


def ensure_report_date(content: str, now: datetime | None = None) -> str:
    """Replace or insert the visible report date with the current local time."""
    text = (content or "").strip()
    if not text:
        return text

    date_line = f"**Date**: {format_local_timestamp(now)}"
    if DATE_LINE_PATTERN.search(text):
        return DATE_LINE_PATTERN.sub(date_line, text, count=1)

    lines = text.splitlines()
    if lines and lines[0].startswith("# "):
        lines.insert(1, "")
        lines.insert(2, date_line)
        return "\n".join(lines)

    return f"{date_line}\n\n{text}"
